chore(raft): introduce snapshot metrics and utilities
zeebe-io/atomix pull request #141
Opened 2020-01-15 10:44 UTC by npepinpe

- adds snapshot replication metrics
- adds SnapshotListener#onSnapshotDeletion (allows tracking removal)

2020-01-15 13:54 UTC, npepinpe commented
Here is how it now looks in Grafana:

![Screenshot from 2020-01-15 14-53-21](https://user-images.githubusercontent.com/43373/72439310-fa338280-37a6-11ea-844b-e20f9163693b.png)

2020-01-16 08:11 UTC, deepthidevaki requested changes
:+1: just one comment.

2020-01-16 08:11 UTC, deepthidevaki commented on protocols/raft/src/main/java/io/atomix/protocols/raft/metrics/SnapshotReplicationMetrics.java
> +          .name("pending_snapshot_milliseconds")
The name `pending_snapshot_milliseconds` is confusing. Better something like `snapshot_replication_duration_milliseconds`.

2020-01-16 10:09 UTC, deepthidevaki approved these changes

2020-01-16 10:13 UTC, npepinpe commented
bors r+

2020-01-16 10:57 UTC, npepinpe commented
bors retry

2020-01-16 11:12 UTC, merged