chore(storage): introduce JournalIndex injection
zeebe-io/atomix pull request #165
Opened 2020-02-26 13:09 UTC by Zelldon

In order to inject own JournalIndex from the outside (from Zeebe) we
 introduce a JournalIndex Supplier which is used in the Journal.
 The RaftPartition, Log etc pass the Supplier to the SegmentedJournal
 which uses that on creating new segments to pass an JournalIndex

 The JournalIndex interface got new method to compact the index. This
 means it removes stored indices lower then the given one. This is the
 opposite operation of truncate.

 On Indexing we use the complete Entry, such that it is possible for
 other Index implementations also take the complete entry into
 account.

This is the preparation for https://github.com/zeebe-io/zeebe/issues/3623

@npepinpe @deepthidevaki actually I don't care who reviews it since you both know about the current topic :smile:

2020-02-26 15:06 UTC, npepinpe requested changes
:+1: 

Looks good. I would propose two things: 

1. Use the factory everywhere - so where we specify the index density, just have it use a `SparseJournalIndexFactory` with that density
1. Not call the supplier on every new segment, but just once when we create the journal - or is this necessary?

2020-02-26 15:06 UTC, npepinpe commented on storage/src/main/java/io/atomix/storage/journal/index/JournalIndex.java
> +  void compact(long index);
Wait, so we never cleared the index after compaction? :scream:

2020-02-26 15:06 UTC, npepinpe commented on storage/src/main/java/io/atomix/storage/journal/SegmentedJournal.java
> +        journalIndexFactory == null ? () -> new SparseJournalIndex(indexDensity)
Why not have the builder's `withIndexDensity` just set the factory to `() -> new SparseJournalIndex(density)`? Do we still need these two parameters?

2020-02-26 15:06 UTC, npepinpe commented on storage/src/main/java/io/atomix/storage/journal/SegmentedJournal.java
> +        journalIndexFactory.get());
Does it make sense to get a new factory every time when getting a new segment? Why not just have the journal factory in the constructor and use the same journal index always?

2020-02-26 15:06 UTC, npepinpe commented on storage/src/main/java/io/atomix/storage/journal/SegmentedJournal.java
> +          segment.compactIndex(index);
Nice catch :muscle:

2020-02-26 15:47 UTC, Zelldon commented
Hey thanks for the quick review @npepinpe 

> Looks good. I would propose two things:
> 1. Use the factory everywhere - so where we specify the index density, just have it use a SparseJournalIndexFactory with that density
> 2. Not call the supplier on every new segment, but just once when we create the journal - or is this necessary?

1. I found that the density is more a property of the SparseJournalIndex unrelated to the JournalIndex, if you accept it on the factory you make it a property of the JournalIndex itself. 
Before I was not think that I need it, but in my current implementation i also use it so yes I an change it if you want.
2. I didn't wanted to change to much. The JournalIndex was created before for each Segment, which is the reason why I build it that way to have the smallest changes possible. It is also the reason why there was no compact before, since each segment has its own index.

2020-02-26 15:48 UTC, npepinpe commented
Ah, so `JournalIndex` is really `JournalSegmentIndex`? :see_no_evil: 

I think regarding 1. I didn't explain what I mean - we both agree, it's a property of `SparseJournalIndex`. So why not have a `SparseJournalIndexFactory` which is created with the density? And set that factory in the journal, instead of passing both the index density and a null journal index factory when we want to use the sparse journal index?

2020-02-27 07:37 UTC, Zelldon commented
Yes you're right. I  have overlooked that in my tunnel yesterday. Thanks for pointing this out. I removed the density completely.

2020-02-27 13:17 UTC, npepinpe approved these changes
:+1:

2020-02-27 13:57 UTC, Zelldon commented
bors r+

2020-02-27 16:17 UTC, Zelldon commented
Bors r+

2020-02-27 16:32 UTC, merged